### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by VenomousReaperGoat** [NaiNonTH/Foliage-Plus#1]
## Describe the Issue:
Transparent line.

## Screenshots:
![image](https://github.com/NaiNonTH/Foliage-Plus/assets/85793899/ca8753c2-3234-4c19-815b-bab6b5fb1859)

## Environment Details:
 - Minecraft Version: *1.20.1*
 - Mods used: *![image](https://github.com/NaiNonTH/Foliage-Plus/assets/85793899/7fdb5413-36c0-4cef-99f7-a52c6ee5fa60)*
 - Resource Pack Version: *![image](https://github.com/NaiNonTH/Foliage-Plus/assets/85793899/08d2ecce-0a36-4965-acbb-b9ba7c6fdf49)*

## Additional Details:
Feel free to add any other useful things outside the topics mentioned.

**Comment by NaiNonTH** [comment]
Seems to be an issue with mod compatibility. I'm not sure which, but I'm suspecting the Chunks fade in mod.

Try removing `Chunks fade in` mod and please let me know if it does fix your issue. :)

**Comment by NaiNonTH** [comment]
Closing this for being inactive
