### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by ghost** [NaiNonTH/Foliage-Plus#2]
## Describe the Issue:
Mod compatibility issue

## Screenshots:
![image](https://github.com/NaiNonTH/Foliage-Plus/assets/146892171/2608a123-8dda-439c-a6e2-88c758c0c678)
![image](https://github.com/NaiNonTH/Foliage-Plus/assets/146892171/78e10cbc-3c99-419f-a733-420c5e12816a)

## Environment Details:
1.19.2
Mods and resources isn't the cause.

## Additional Details:
BYG works fine.
Harvestcraft and BOP and twilight works like shown.
Leaves blocks works fine. 
On 1.18.2 all works fine.

**Comment by NaiNonTH** [comment]
It really is broken. I'll try to look into it. Still have no idea, though.

**Comment by NaiNonTH** [comment]
Did some research, and I found this:
```
"render_type": "minecraft:cutout",
```
Seems like the Forge 1.19+ has added the `render_type`  and mods such as BOP, Twilight, and PH are using it. My pack has none of that so that's the thing.
I'll let you know when I fix it.

**Comment by ghost** [comment]
Also half of BYG leaves isnt supported and that is supported missing texture. And no butterflies.
![image](https://github.com/NaiNonTH/Foliage-Plus/assets/146892171/22fd2130-159b-4f34-b710-31bfe79df5f8)
![image](https://github.com/NaiNonTH/Foliage-Plus/assets/146892171/0d54ae99-73be-40d0-8841-0839455dc7df)

**Comment by NaiNonTH** [comment]
> And no butterflies.

Butterflies aren't available in the normal Foliage+ pack. You need to install the [tweaks](https://modrinth.com/resourcepack/foliage+-tweaks) version too.

**Comment by NaiNonTH** [comment]
Oh, and the tweaks version doesn't have mods support.

**Comment by ghost** [comment]
I have tweaks and i know about mod support its regular yellow flowers on screenshot and things like mushrooms on trees and gravel and sand works fine.

**Comment by NaiNonTH** [comment]
Sorry for taking you so long, but here's the fixed one. Please test them out and let me know if there's anything I missed out.

[Foliage+ V1.5.9.4 +TEST.zip](https://github.com/NaiNonTH/Foliage-Plus/files/12934109/Foliage%2B.V1.5.9.4.%2BTEST.zip)
[Foliage+ Mod Supports +TEST.zip](https://github.com/NaiNonTH/Foliage-Plus/files/12934119/Foliage%2B.Mod.Supports.%2BTEST.zip)

P.S. I didn't provide a fix for BYG (even a test), since I couldn't get the mod to work :(

**Comment by ghost** [comment]
Thanks, Its mostly works fine.
BOP:  Glowflover still funny.
PAM: eggplant miss texures on all stages except fully grown.
TWF: mushgloom funny and darkwood leaves have no bushines.
BYG: ripe, flowering baobab, white mangrove, flowering skyris, flowering joshua have no bushiness.
flowering orchard, ripe joshua, zelkova, willow, skyris, redwood, witch hazel, rainbow eucaliptus, pine, maple, nightshade, palm, jacaranda, mahogany, lament, holly, holly berry, green enchanted, cika, blue enchanted, baobab, fir, ether, ebony, cypress, aspen, ripe orchard leaves missing textures, but other leaves from BYG works fine orange birch leaves for example mb it helps with fix.
![image](https://github.com/NaiNonTH/Foliage-Plus/assets/146892171/c92fe842-5e20-4b2e-8f14-0fc589186cea)

**Comment by NaiNonTH** [comment]
Fixes for 3 mods are provided (excluding the BYG) and are uploaded. Thank you! :)

**Comment by NaiNonTH** [comment]
P.S. If I got BYG working, I may provide a fix for that mod too.
